# Generated by Django 5.2.4 on 2025-07-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendsiteuser',
            name='interaction_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
