# Generated by Django 5.2.4 on 2025-12-08 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recommendsiteuser_interaction_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['title', 'release_year', 'release_date', 'baseline_score', 'description']},
        ),
        migrations.RemoveIndex(
            model_name='game',
            name='core_game_genre_5a70b7_idx',
        ),
        migrations.RemoveField(
            model_name='game',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='game',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='game',
            name='price',
        ),
        migrations.AddField(
            model_name='game',
            name='baseline_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='game',
            name='release_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='developers',
            field=models.ManyToManyField(related_name='games', to='core.developer'),
        ),
        migrations.AddField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(related_name='games', to='core.genre'),
        ),
        migrations.AddField(
            model_name='game',
            name='platforms',
            field=models.ManyToManyField(related_name='games', to='core.platform'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['title'], name='core_game_title_f0d5e2_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['release_year'], name='core_game_release_d558fa_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['baseline_score'], name='core_game_baselin_cf7c87_idx'),
        ),
    ]
