# Generated by Django 5.2.4 on 2025-12-08 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_developer_genre_platform_alter_game_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['title', 'release_year', 'release_date', 'baseline_score']},
        ),
    ]
